export const pacientesIniciales = [
  {
    id: "1",
    nombre: "Juan",
    apellido: "Figueroa Vela",
    edad: "35",
    genero: "Masculino",
    telefono: "9876543210",
    email: "juan.figueroa@ejemplo.com",
    direccion: "Av. Principal 123",
  },
  {
    id: "2",
    nombre: "María",
    apellido: "Rodríguez López",
    edad: "28",
    genero: "Femenino",
    telefono: "9876543211",
    email: "maria.rodriguez@ejemplo.com",
    direccion: "Calle Secundaria 456",
  },
  {
    id: "3",
    nombre: "Carlos",
    apellido: "Gómez Pérez",
    edad: "42",
    genero: "Masculino",
    telefono: "9876543212",
    email: "carlos.gomez@ejemplo.com",
    direccion: "Jr. Los Pinos 789",
  },
  {
    id: "4",
    nombre: "Ana",
    apellido: "Martínez Sánchez",
    edad: "31",
    genero: "Femenino",
    telefono: "9876543213",
    email: "ana.martinez@ejemplo.com",
    direccion: "Av. Las Flores 234",
  },
  {
    id: "5",
    nombre: "Pedro",
    apellido: "Díaz Torres",
    edad: "45",
    genero: "Masculino",
    telefono: "9876543214",
    email: "pedro.diaz@ejemplo.com",
    direccion: "Calle Los Olivos 567",
  },
  {
    id: "6",
    nombre: "Laura",
    apellido: "Fernández Ruiz",
    edad: "29",
    genero: "Femenino",
    telefono: "9876543215",
    email: "laura.fernandez@ejemplo.com",
    direccion: "Jr. Las Palmeras 890",
  },
  {
    id: "7",
    nombre: "Miguel",
    apellido: "Hernández Castro",
    edad: "38",
    genero: "Masculino",
    telefono: "9876543216",
    email: "miguel.hernandez@ejemplo.com",
    direccion: "Av. Central 345",
  },
  {
    id: "8",
    nombre: "Sofía",
    apellido: "Vargas Morales",
    edad: "33",
    genero: "Femenino",
    telefono: "9876543217",
    email: "sofia.vargas@ejemplo.com",
    direccion: "Calle Los Cedros 678",
  },
  {
    id: "9",
    nombre: "Javier",
    apellido: "Ortega Mendoza",
    edad: "41",
    genero: "Masculino",
    telefono: "9876543218",
    email: "javier.ortega@ejemplo.com",
    direccion: "Jr. Las Azucenas 901",
  },
  {
    id: "10",
    nombre: "Carmen",
    apellido: "Navarro Jiménez",
    edad: "36",
    genero: "Femenino",
    telefono: "9876543219",
    email: "carmen.navarro@ejemplo.com",
    direccion: "Av. Los Laureles 234",
  },
  {
    id: "11",
    nombre: "Roberto",
    apellido: "Ramos Gutiérrez",
    edad: "44",
    genero: "Masculino",
    telefono: "9876543220",
    email: "roberto.ramos@ejemplo.com",
    direccion: "Calle Los Robles 567",
  },
  {
    id: "12",
    nombre: "Patricia",
    apellido: "Flores Medina",
    edad: "30",
    genero: "Femenino",
    telefono: "9876543221",
    email: "patricia.flores@ejemplo.com",
    direccion: "Jr. Las Margaritas 890",
  },
]
